services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}  # Passing GitHub token during build
    networks:
      - db_network
      - web_network
    env_file:
      - .env  # Loading environment variables, including GITHUB_TOKEN
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
