# Automation: The Blueprint ensures that every time you push changes to your
# repository, Render knows how to deploy your services and infrastructure
# automatically. It removes the need for manually configuring servers or
# services every time you make changes to your app. You can manage
# deployments and changes using the blueprint, making it consistent and scalable


# The database is hosted on Render.
# You don’t have to install or manage PostgreSQL manually because Render handles
# backups, updates, and scaling. You only need to define the database in your
# render.yaml file and configure your app to point to it using the
# DATABASE_URL environment variable.



ervices:
  - type: web
    name: ElieComMyOtherJob
    plan: starter
    env: python
    region: virginia  # Ensure this matches your database region
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: eliecom_myotherjob_db
          property: connectionString

databases:
  - name: eliecom_myotherjob_db
    plan: starter
    region: virginia  # Same region as your service
