# Generated by Django 5.0.4 on 2024-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=246)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic')], max_length=20)),
            ],
        ),
    ]
